/**   CompilationEngine.h
 *    Recursive top-down parser.
 *    matthew.james.bird@gmail.com
 */

#ifndef compilationEngine_h
#define compilationEngine_h

/** 
 *  Effects the actual compilation output. Gets its input from Tokeniser and
 *  emits its parsed struture into an output file. The output is generated by
 *  a series of compilexxx() routines, one for every syntactic element xxx of
 *  the Jack grammar. The contract between these routines is that each
 *  compilexxx() routine should read the syntactic construct xxx from the input,
 *  advance() the tokeniser exactly beyond xxx, and output the parsing of xxx.
 *  Thus, compilexxx() may only be called if indeed xxx is the next syntactic
 *  element of the input.
 */
class CompilationEngine {
public:

};

#endif // compilationEngine_h    
